name: Daily Build PHP-Apache Images

on:
  schedule:
    - cron: '0 0 * * *'  # Täglicher Build
  workflow_dispatch:  # Manuelles Triggern

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: [8.0, 8.1, 8.2, 8.3, 8.4]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php-fpm-apache:${{ matrix.php_version }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
